#!/bin/bash
# VPSForge v1.0.0 — Guest network configuration.

wait_guest_eth0() {
  local name="$1" i
  for i in $(seq 1 30); do
    incus exec "$name" -- ip link show dev eth0 >/dev/null 2>&1 && return 0
    sleep 1
  done
  return 1
}

apply_guest_static_network() {
  local name="$1" ip="$2" gateway="$3" prefix="${4:-24}"

  # Convert CIDR prefix to netmask
  local mask=""
  local full_octets=$((prefix / 8))
  local partial_bits=$((prefix % 8))
  local i
  for ((i=0; i<4; i++)); do
    if [ $i -lt $full_octets ]; then
      mask+="${mask:+.}255"
    elif [ $i -eq $full_octets ]; then
      local val=$(( 256 - (1 << (8 - partial_bits)) ))
      mask+="${mask:+.}$val"
    else
      mask+="${mask:+.}0"
    fi
  done

  # 1. Netplan config (Ubuntu, Debian newer)
  if incus exec "$name" -- sh -c 'command -v netplan >/dev/null 2>&1'; then
    incus exec "$name" -- sh -c '
      set -e
      mkdir -p /etc/netplan
      cat > /etc/netplan/99-vpsforge.yaml <<EOF
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: no
      mtu: 1420
      addresses:
        - "'"$ip"'/'"$prefix"'"
      routes:
        - to: default
          via: "'"$gateway"'"
      nameservers:
        addresses:
          - 1.1.1.1
          - 8.8.8.8
EOF
      chmod 600 /etc/netplan/99-vpsforge.yaml
      netplan generate >/dev/null 2>&1 || true
    ' || echo "WARNING: Netplan configuration generation failed in $name."
  fi

  # 2. systemd-networkd config (Arch, Rocky/Alma/Fedora/Debian alternative)
  if incus exec "$name" -- sh -c 'test -d /etc/systemd/network'; then
    incus exec "$name" -- sh -c '
      set -e
      cat > /etc/systemd/network/99-vpsforge.network <<EOF
[Match]
Name=eth0

[Network]
Address='"$ip"'/'"$prefix"'
Gateway='"$gateway"'
DNS=1.1.1.1
DNS=8.8.8.8
EOF
      chmod 644 /etc/systemd/network/99-vpsforge.network
      if command -v systemctl >/dev/null 2>&1; then
        systemctl restart systemd-networkd >/dev/null 2>&1 || true
      fi
    ' || echo "WARNING: systemd-networkd configuration failed in $name."
  fi

  # 3. Interfaces / ifupdown config (Alpine, Debian/Ubuntu legacy fallback)
  if incus exec "$name" -- sh -c 'test -d /etc/network'; then
    incus exec "$name" -- sh -c '
      set -e
      if [ -f /etc/network/interfaces ]; then
        if ! grep -q "vpsforge" /etc/network/interfaces; then
          cp /etc/network/interfaces /etc/network/interfaces.bak 2>/dev/null || true
        fi
      fi
      cat > /etc/network/interfaces <<EOF
# Configuration generated by VPSForge
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet static
    address '"$ip"'
    netmask '"$mask"'
    gateway '"$gateway"'
    dns-nameservers 1.1.1.1 8.8.8.8
EOF
      chmod 644 /etc/network/interfaces
    ' || echo "WARNING: /etc/network/interfaces configuration failed in $name."
  fi

  # 4. NetworkManager Keyfile config (Rocky, Alma, Fedora newer)
  if incus exec "$name" -- sh -c 'test -d /etc/NetworkManager/system-connections'; then
    incus exec "$name" -- sh -c '
      set -e
      cat > /etc/NetworkManager/system-connections/vpsforge-eth0.nmconnection <<EOF
[connection]
id=vpsforge-eth0
uuid=73a38ff1-789a-4c22-b5cc-485db1f94c48
type=ethernet
interface-name=eth0

[ethernet]
cloned-mac-address=preserve

[ipv4]
method=manual
address1='"$ip"'/'"$prefix"','"$gateway"'
dns=1.1.1.1;8.8.8.8;

[ipv6]
method=ignore
EOF
      chmod 600 /etc/NetworkManager/system-connections/vpsforge-eth0.nmconnection
      if command -v nmcli >/dev/null 2>&1; then
        nmcli connection reload >/dev/null 2>&1 || true
        nmcli connection up vpsforge-eth0 >/dev/null 2>&1 || true
      fi
    ' || echo "WARNING: NetworkManager keyfile configuration failed in $name."
  fi

  # 5. Legacy sysconfig network-scripts (CentOS/Rocky/Alma legacy)
  if incus exec "$name" -- sh -c 'test -d /etc/sysconfig/network-scripts'; then
    incus exec "$name" -- sh -c '
      set -e
      cat > /etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF
DEVICE=eth0
BOOTPROTO=none
ONBOOT=yes
IPADDR='"$ip"'
PREFIX='"$prefix"'
GATEWAY='"$gateway"'
DNS1=1.1.1.1
DNS2=8.8.8.8
EOF
      chmod 644 /etc/sysconfig/network-scripts/ifcfg-eth0
    ' || echo "WARNING: Legacy network scripts configuration failed in $name."
  fi

  # Immediate runtime network application via IP commands
  incus exec "$name" -- sh -c '
    set -e
    ip link set eth0 mtu 1420 2>/dev/null || true
    ip link set eth0 up
    ip -4 addr flush dev eth0 scope global || true
    ip -4 addr add '"$ip"'/'"$prefix"' dev eth0
    ip route replace default via '"$gateway"' dev eth0
    ip -4 addr show dev eth0 | grep -Fq -- "'"$ip"'/'"$prefix"'"
    ip -4 route show default | grep -Fq -- "default via '"$gateway"' dev eth0"
  ' || {
    echo "ERROR: ip-based guest network setup failed inside $name."
    return 1
  }

  return 0
}

configure_guest_dns() {
  local name="$1"
  incus exec "$name" -- sh -c '
    set -e
    rm -f /etc/resolv.conf
    cat > /etc/resolv.conf <<EOF
nameserver 1.1.1.1
nameserver 8.8.8.8
options edns0 trust-ad
EOF
    chmod 644 /etc/resolv.conf
  ' || {
    echo "ERROR: Failed to configure DNS inside $name."
    return 1
  }
}
